language: node_js
node_js:
- '6'
- '8'
- '10'
deploy:
  provider: npm
  api_key:
    secure: eSdw0YOKx6J20I5WEeTvgeBvv1vYKctiIsN2ZqgGVx4hlJ/3/64qR3LF2+neTWg/4kkp/2X6ngRxVfGNJ6qK8rv5RpeS07zsE1nlhrWeCB7yieglmzKdaCKewen66+dnXJiq9se4Iegrr/NIpO2lqn9LyhBgsnPq940wwr++R0Ceqy3rT+Tmg3L/leXQv7b+8KgoYncv3l9Ef2T/ouMYkp7F7Ppo9NbGF3o2HbceEg/Q1nZYogiTKW1CABYGDM8wCPbdv9ojef8yVvlgwTH1I3e9tEOtS/RoMq3WXlSbWnkixCx11dsdzyEPzc9KzQoKYbYQR6cSO50L6FFNlOnQivCXxIFZrHxFapcnAnqXhQOI0N5YbrXnTgEQPkt/A+pHGCMKahQRIoi2fihInLWte+3k8kuElqOgu/C9KWzVkE/NA29msp7WYmaTPgmwvTlCtdDdJitzc4xJELkS2MqxugnGRzUN++qz2Ixk15KGyNLa8IXdLG2nNx4RVZcxNV1nKGC8IqyqrOJ3PYNlKGQ9EpL0fL3QlWZJJqyyC6TTcq0i0Dlanf+v7Jk3zlESAFYPZewAvvLWy/thJmD6k5U9305bkLfzwbjqyBHGEi29k5v/bgDsDdES+cANrhvrSH4SyktZ8iBKQEKYYSK9pjgFvzntG5QO/xnIWt6cNLpYi7g=
  email: julian@dotcore.co.il
  skip_cleanup: true
  on:
    tags: true
after_success:
- npm run coveralls
