name: release
on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test

    - name: Publish
      uses: mmarchini-oss/npm-otp-publish@v0
      with:
        npm_token: ${{ secrets.NPM_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        github_actor: ${{ github.actor }}
